

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: metavite
  labels:
     app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      
      containers:
      - name: auth
        image: jaydee47/auth-service:0.0.0.RELEASE
        ports:
        - containerPort: 3001
        env:
        

        
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: authorization-service-mongo-config
              key: MONGO_URI
          
        - name: JWT_SECRET
          value: '9074297611'

         # RabbitMQ Configuration
        - name: RABBITMQ_HOST
          # value: "10.244.0.6"
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-port
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-password
        - name: RABBITMQ_URI
          value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)


        
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: metavite
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: auth-service

