apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: metavite
data:
  rabbitmq-user: YWRtaW4=   # Base64-encoded "admin"
  rabbitmq-password: c2VjcmV0   # Base64-encoded "secret"
  EMAIL_PASSWORD: dGV4d3N0ZWl6bHVuaHBrYw==

   # Razorpay secrets
  RAZORPAY_KEY_ID: cnpwX3Rlc3RfclBSQlRFMTRjMXpVcEs=
  RAZORPAY_KEY_SECRET: QXlLTTQ5YWRsWmR1aHY0WWJEVmloc3Nj
  RAZORPAY_X_KEY_ID: cnpwX3Rlc3RfazJETjhkYjZXU21oVXo=
  RAZORPAY_X_KEY_SECRET: bTVVVGg5V0xBVjhwZDgybjBVSGNBV0t1
  RAZORPAY_VIRTUAL_ACCOUNT_NUMBER: MjMyMzIzMDA1MTYxNTg0OA==




