

apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-service
  namespace: metavite
  labels:
     app: load-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-service
  template:
    metadata:
      labels:
        app: load-service
    spec:
      
      containers:
      - name: load-service
        image: jaydee47/load-service:0.0.0.RELEASE
        ports:
        - containerPort: 5001  # Socket.IO
        - containerPort: 3007  # gRPC
        env:
        

        
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: load-service-mongo-config
              key: MONGO_URI
          
        - name: JWT_SECRET
          value: '9074297611'

         # RabbitMQ Configuration
        - name: RABBITMQ_HOST
          # value: "10.244.0.6"
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-config
              key: rabbitmq-port
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-password
        - name: RABBITMQ_URI
          value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@$(RABBITMQ_HOST):$(RABBITMQ_PORT)


        
---
apiVersion: v1
kind: Service
metadata:
  name: load-service
  namespace: metavite
spec:
  type: ClusterIP
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: socketio
    - port: 3007
      targetPort: 3007
      protocol: TCP
      name: grpc
  selector:
    app: load-service

